name: pharmaplus_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  shimmer: ^3.0.0
  google_sign_in: ^7.1.1
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo/

# 👇 Put this OUTSIDE the flutter: section (same indentation level)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
