// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwhz89OFnn4gPJ8lBldnYm9fdTLfBQXhI',
    appId: '1:901858029123:web:3c38be19cf8b57eb2faef6',
    messagingSenderId: '901858029123',
    projectId: 'pharma-plus-3548b',
    authDomain: 'pharma-plus-3548b.firebaseapp.com',
    storageBucket: 'pharma-plus-3548b.firebasestorage.app',
    measurementId: 'G-J2QT17C7XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHqK8eBpCNkExEInsk_LI7iIGDuXNTqhM',
    appId: '1:901858029123:android:32b22caa6274304d2faef6',
    messagingSenderId: '901858029123',
    projectId: 'pharma-plus-3548b',
    storageBucket: 'pharma-plus-3548b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6r6MXO36sCDOzKqYnrEoX-s05amH90R4',
    appId: '1:901858029123:ios:94cacd96130b00fb2faef6',
    messagingSenderId: '901858029123',
    projectId: 'pharma-plus-3548b',
    storageBucket: 'pharma-plus-3548b.firebasestorage.app',
    iosBundleId: 'com.example.pharmaplusFlutter',
  );
}
